name: hooks
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  async: ^2.11.0
  mason: any
  process_run: ^0.12.5+3
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
